### ISSUE TITLE
Processed data release

### ISSUE THREAD

**Issue by xiao2mo** [tsujuifu/pytorch_violet#10]
Hi, Thanks for ur great work.
Please release all related processed data like many other works, if it's convenient for u.

**Comment by tsujuifu** [comment]
We have provided all [downstream](https://drive.google.com/drive/u/2/folders/1BisJHVUOLeHWmnAeMrCHvy1BP9XBXNkQ) and [pretraining](https://drive.google.com/drive/u/2/folders/1PCFBPaIS_2UhFsv7n9L5CYS1wg_dfQF2) datasets.
