### ISSUE TITLE
Question about the img_tgif.pkl file.

### ISSUE THREAD

**Issue by jhkang727** [tsujuifu/pytorch_violet#13]
Hello, thank you for your code.

I was trying to implement VIOLET on Next-QA dataset. However I couldn't find out how to make pkl file in '_data' folder.
I was wondering if I can get the code that makes img_<dataset>.pkl files.

**Comment by tsujuifu** [comment]
You can check [this](https://github.com/tsujuifu/pytorch_violet/blob/main/_tools/extract_video-frame.py) to extract frames from a video and **save them as a PKL file**.

**Comment by jhkang727** [comment]
Thanks for the reply. Then can I use the same nextqa.pkl file as img_nextqa.pkl?

**Comment by tsujuifu** [comment]
I believe Yes if all the formats are correct and matched.

**Comment by jhkang727** [comment]
It works!
Thank you so much.
