### ISSUE TITLE
zero-shot evaluation (video retrieval)

### ISSUE THREAD

**Issue by avinashsai** [tsujuifu/pytorch_violet#15]
Hello,

Congratulations on the amazing work. I have a few questions about zero-shot evaluation in Table-1.

1. Which checkpoint is used for zero-shot evaluation?
2. The retrieval model has fully connected layers on the top of VIOLET Base model? In zero-shot evaluation, are these layers randomly initialized?
3. If I need separate video and text features,  which layer outputs are the most suitable (EncImg / EncTxt /Cross transformer)?

Thank you.

**Comment by tsujuifu** [comment]
Hi Avinash, 

1. The [pre-trained one](https://drive.google.com/uc?id=1RLbthdRIflxCFjRTcVV5jQJGP30_lNfg) is used for zero-shot evaluation.
2. We use the [FC layer](https://github.com/tsujuifu/pytorch_violet/blob/main/main_pretrain.py#L70) (for VTM), which is trained during the pre-training.
3. [Here](https://github.com/tsujuifu/pytorch_violet/blob/main/model.py#L56) should be the separate features before cross-modal fusion.

**Comment by avinashsai** [comment]
Hi Tsu-Jui,

Thanks for your reply. 
3. Just curious about this: If VIOLET is to evaluated on a totally different multi-modal (requires both video & text features) task in a zero-shot setting, which features are recommended, (video - text or video - cross modal)

**Comment by tsujuifu** [comment]
If that is the case, I will suggest using the [fused features](https://github.com/tsujuifu/pytorch_violet/blob/main/model.py#L64), which consider both vision and language perception.

**Comment by avinashsai** [comment]
You mean [video outputs](https://github.com/tsujuifu/pytorch_violet/blob/main/model.py#L57) and [fused features](https://github.com/tsujuifu/pytorch_violet/blob/main/model.py#L64)?

**Comment by tsujuifu** [comment]
Yes
