### ISSUE TITLE
Some metadata files are missing

### ISSUE THREAD

**Issue by cmh1027** [tsujuifu/pytorch_violet#16]
Hello, where can I get missing metadata files like txt_msvd-retrieval.json, args_msrvtt-qa.json, or args_msvd-retrieval.json, etc? Should I make those by myself?
In addition, how can I evaluate qa? It seems only evaluation code for retrieval is provided

**Comment by tsujuifu** [comment]
Hi, we did not do text-to-video retrieval on the MSVD dataset.
The args for each dataset are similar to the template in [_data](https://github.com/tsujuifu/pytorch_violet/tree/main/_data). You can edit it for your own needs.
[main_qamc.py](https://github.com/tsujuifu/pytorch_violet/blob/main/main_qamc.py) and [main_qamc.py](https://github.com/tsujuifu/pytorch_violet/blob/main/main_qamc.py) also include the validation/testing process. You can replace **path_ckpt** as your trained checkpoint to do the evaluation.

**Comment by cmh1027** [comment]
Thank you!
