### ISSUE TITLE
Rank Errors in pre-training

### ISSUE THREAD

**Issue by 00asuka** [tsujuifu/pytorch_violet#17]
`CUDA_VISIBLE_DEVICES='0,1,2,3' python -m torch.distributed.launch --nproc_per_node=4 --master_port=7122 main_pretrain.py`
When I tried to run this, a rank error occurred. Do I need to specify the rank somewhere?

Errors are the following
```
usage: main_pretrain.py [-h] [--local_rank LOCAL_RANK]
usage: main_pretrain.py [-h] [--local_rank LOCAL_RANK]
usage: main_pretrain.py [-h] [--local_rank LOCAL_RANK]
main_pretrain.py: error: unrecognized arguments: --local-rank=1
main_pretrain.py: error: unrecognized arguments: --local-rank=0
main_pretrain.py: error: unrecognized arguments: --local-rank=3
usage: main_pretrain.py [-h] [--local_rank LOCAL_RANK]
main_pretrain.py: error: unrecognized arguments: --local-rank=2
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 1499185) of binary: /bin/python

```

**Comment by tsujuifu** [comment]
Hi, it looks like you are using a newer PyTorch version (we are using **torch==1.7**).
Maybe try [torchrun](https://pytorch.org/docs/stable/elastic/run.html) instead of torch.distributed.launch in your case.
