### ISSUE TITLE
Could you provide the script for generating 'txt_xxx.json' in '_data'

### ISSUE THREAD

**Issue by ruiyan1995** [tsujuifu/pytorch_violet#3]

**Comment by tsujuifu** [comment]
Since each dataset has its original JSON file, the scripts should be different (but not too difficult, I believe).
The _txt_xxx.json_  is provided as the **example format** to follow.

**Comment by ruiyan1995** [comment]
Thanks for your reply. Yes, but some of the details are different. For example, each video in MSRVTT-retrieval has more than one captions. Do you use the fisrt one or choose one at random in this work?

**Comment by tsujuifu** [comment]
Thanks for pointing this out! 

Yes. MSRVTT-Retrieval has 10 captions for each video, and we **treat them as independent items**.
Therefore, the JSON file should be like:
```json
{
  "train": [
    {
      "video": "vid1",
      "caption": "cap1"
    },
    {
      "video": "vid1",
      "caption": "cap2"
    },
    {
      "video": "vid1",
      "caption": "cap3"
    },
    {
      "video": "vid2",
      "caption": "cap1"
    },
    {
      "video": "vid2",
      "caption": "cap2"
    },
    {
      "video": "vid2",
      "caption": "cap3"
    }
  ],
  "val": [],
  "test": []
}
```
For example, there are two captions for _video5029_ in [txt_msrvtt-retrieval.json](https://github.com/tsujuifu/pytorch_violet/blob/main/_data/txt_msrvtt-retrieval.json).

**Comment by ruiyan1995** [comment]
Thanks. But I cannot reproduce the results of zero-shot retrieval on MSRVTT.
I use the following settings:
1, JSfusion (9000 for train and 1000 for test)
2, For test, we choose the first caption as same as "Frozen in Time" [details at here](https://github.com/m-bain/frozen-in-time/blob/main/data_loader/MSRVTT_dataset.py#L69)
3, load the best ckpt provided by you

I can only get `test {'r@1': 0.22200000000000017, 'r@5': 0.5130000000000003, 'r@10': 0.6680000000000005, 'median': 5}` of zero-shot retrieval on MSRVTT.

**Comment by tsujuifu** [comment]
Let me check it. 
The result is interesting where R@5 and R@10 are even higher than proposed 😂

Please first make sure that we use **5-sampled video frames** and **frame size 224** for downstream tasks.

**Comment by ruiyan1995** [comment]
Yes, I confirm.

**Comment by ruiyan1995** [comment]
@tsujuifu Hi, I have checked again. I used specific caption idx's in jsfusion provided by "jsfusion_val_caption_idx.pkl". So I want to know how do you get caption during testing on MSRVTT?

**Comment by tsujuifu** [comment]
We directly adopt from [ClipBERT](https://arxiv.org/pdf/2102.06183.pdf), so it should be the same as [JSFusion](https://arxiv.org/pdf/1808.02559.pdf).

**Comment by ruiyan1995** [comment]
Thanks for your kindly helps. I have repoduced the results of MSRVTT-retrieval (R@1: 33.7) with finetuned ckpt (provided by you), but still cannot get promising results on the zero-shot setting.

**Comment by chenbiaolong** [comment]
@tsujuifu can you provide the whole txt_msrvtt-retrieval.json you use? I can't repoduce the result of downstream task of MSRVTT-retrieval use your best pretrained [ckpt](https://drive.google.com/file/d/1RLbthdRIflxCFjRTcVV5jQJGP30_lNfg/view?usp=sharing). I want to make sure I use the right train&test data

**Comment by tsujuifu** [comment]
[Here](https://drive.google.com/file/d/1e-d5ADytvRKetxsvKDqqsqsEWWxRLaow/view?usp=sharing) is my used **txt_msrvtt-retrieval.json**
