### ISSUE TITLE
I found some wrong places, can you see if it's right?

### ISSUE THREAD

**Issue by bubbliiiing** [tsujuifu/pytorch_violet#4]
In main_pretrain.py, line 165:
`p = (1+_h*_w)*i_t + i_h*_w + i_w`
I think it should plus 1.
`p = (1+_h*_w)*i_t + i_h*_w + i_w + 1`
Because your first position is for the separator.

**Comment by bubbliiiing** [comment]
Already stared your code, thanks for you contribution.

**Comment by tsujuifu** [comment]
Yep, thanks for pointing it out!
We have **a [CLS_V] token** in front of each video frame, so it should **+1**.

**Comment by bubbliiiing** [comment]
OK, thank you
