### ISSUE TITLE
Treat FFOE Video QA as a classifcation task on answers candidate set

### ISSUE THREAD

**Issue by jiyt17** [tsujuifu/pytorch_violet#8]
Violet uses most commen answers as candidates, but there are other answers in the test set. How do you deal with them? Are they abandoned according to the txt_msvd.json?

**Comment by doc-doc** [comment]
I have checked the code and data. It seems that the authors just keep the Top-1k answers (MSVD-QA) and remove the unseen-answer samples . It is certainly not a standard and will give rise to unreasonably higher results than others. I thus doubt about the fairness of the comparison in the paper.
Please correct me if I am wrong, or othewise the authors need to revise their evaluation & results..

**Comment by tsujuifu** [comment]
Super thanks for the clarification!
After checking it, there is exactly a performance error for QAOE in the original [VIOLET](https://arxiv.org/abs/2111.12681).
In our new [Empirical-MVM](https://arxiv.org/abs/2209.01540), we have fixed it (treat all questions in the testing set), and the accuracy is correct.
We will release the code of Empirical-MVM soon 😊
