### ISSUE TITLE
Swin Base or Small

### ISSUE THREAD

**Issue by vateye** [tsujuifu/pytorch_violet#9]
Hi, I have noticed that the output original Swin-Base is 1024, but according to your code, the output is 768. Did you use the Swin Small for experiment?

**Comment by tsujuifu** [comment]
Thanks for pointing this out!

We are using **Swin-S** as [here](https://github.com/SwinTransformer/storage/releases/download/v1.0.4/swin_small_patch244_window877_kinetics400_1k.pth).

**Comment by vateye** [comment]
So in the paper, did you refer Swin small as Swin base? Same question for LAVENDER? @linjieli222

**Comment by tsujuifu** [comment]
Not sure about LAVENDER.

In VIOLET, that is my mistake 😅
I first thought I was using Swin-B, but it is Swin-S in our implementation.

Sorry for the misunderstanding.
We will update our arXiv paper!

**Comment by vateye** [comment]
Thanks. But also looking forward to seeing the reply about LAVENDER from @linjieli222.

**Comment by linjieli222** [comment]
> Thanks. But also looking forward to seeing the reply about LAVENDER from @linjieli222.

In LAVENDER, Swin-base is used. Not Swin-small.
